[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "argoPlot-Script"
authors = [{name = "db", email = "db@brin.go.id"}]
dynamic = ["version", "description"]
